concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v4
      with:
        key: maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: 'maven-

          '
    - continue-on-error: true
      env:
        MAVEN_OPTS: --add-opens java.base/java.util=ALL-UNNAMED
      name: Build with Maven
      run: mvn clean test spotless:check javadoc:javadoc
    - continue-on-error: true
      if: always()
      name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      with:
        annotate_notice: false
        check_name: Test report ${{ matrix.java }}
        report_paths: '**/target/surefire-reports/TEST-*.xml'
    strategy:
      matrix:
        java:
        - '17'
        - '21'
name: CI
on:
  repository_dispatch:
    types: trigger-ga___build.yml
